version: '3'
services:
  api:
    image: "api:${DOCKER_TAG:-latest}"
    build:
      context: ./
    container_name: api_test
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8000:8000"